Fix getOutputReport, getInputReport and getFeatureReport: not being able to create more than one report + temporal coupling
h2zero/NimBLE-Arduino pull request #812
Opened 2024-12-17 11:44 UTC by afpineda

This fix is related to Issue #805 in the `NimBLEHIDDevice` class.

*What fixes*:

- The user can call `getXXXXXReport()` in any order.
- The user gets a different characteristic for each different reportID.
- The user gets the same characteristic for the same reportID.

*Fix description*:

A new private method is introduced: `locateReportCharacteristicById()`: given a `reportID`, it returns the characteristic if already created, nullptr otherwise.
`getXXXXXReport()` tries to locate the characteristic. If found, it is returned "as is". If not found, it is created and returned.

*Drawbacks*:
There is a computational overhead. The user should store/cache the value returned by `getXXXXXReport()` instead of repeating the calls. Perhaps we should warn about this in the documentation.

2024-12-17 14:25 UTC, h2zero commented
https://github.com/h2zero/NimBLE-Arduino/pull/805#issuecomment-2548600648

2024-12-18 21:38 UTC, h2zero requested changes
Looks good, just a minor comment. Also can you please check the formatting, if in vscode you can just right click and format document.

2024-12-18 21:38 UTC, h2zero commented on .gitignore
> +.development
Can we remove this?

2024-12-19 07:46 UTC, afpineda commented on .gitignore
> +.development
> Can we remove this?

Sorry, no. Arduino does not allow you to edit a library unless the ".development" file is in the library folder, but at the same time it does not allow you to include the file in the repo.
See the [Arduino library specification](https://docs.arduino.cc/arduino-cli/library-specification/), section "Development flag file".
Note that I'm using a clone of your repo as a library for my own sketches.

It does no harm to anybody.

2024-12-19 17:30 UTC, merged

2024-12-19 17:31 UTC, h2zero commented
Thank you @afpineda !